<?php
namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BarangSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('barang')->insert([
            [
                'id_kategori' => 1,
                'kode_barang' => 'ELK-001',
                'nama_barang' => 'Laptop Lenovo',
                'satuan' => 'unit',
                'harga_beli' => 8000000,
                'harga_jual' => 9000000,
                'stok_min' => 2,
                'stok_saat_ini' => 10,
                'gambar' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategori' => 1,
                'kode_barang' => 'ELK-002',
                'nama_barang' => 'Printer Epson',
                'satuan' => 'unit',
                'harga_beli' => 2000000,
                'harga_jual' => 2500000,
                'stok_min' => 1,
                'stok_saat_ini' => 5,
                'gambar' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategori' => 2,
                'kode_barang' => 'ALT-001',
                'nama_barang' => 'Pulpen Pilot',
                'satuan' => 'pcs',
                'harga_beli' => 5000,
                'harga_jual' => 7000,
                'stok_min' => 20,
                'stok_saat_ini' => 100,
                'gambar' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategori' => 2,
                'kode_barang' => 'ALT-002',
                'nama_barang' => 'Buku Tulis Sidu',
                'satuan' => 'pcs',
                'harga_beli' => 3000,
                'harga_jual' => 5000,
                'stok_min' => 30,
                'stok_saat_ini' => 200,
                'gambar' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategori' => 3,
                'kode_barang' => 'BBK-001',
                'nama_barang' => 'Kertas HVS',
                'satuan' => 'rim',
                'harga_beli' => 40000,
                'harga_jual' => 50000,
                'stok_min' => 10,
                'stok_saat_ini' => 50,
                'gambar' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategori' => 3,
                'kode_barang' => 'BBK-002',
                'nama_barang' => 'Tinta Printer',
                'satuan' => 'botol',
                'harga_beli' => 60000,
                'harga_jual' => 75000,
                'stok_min' => 5,
                'stok_saat_ini' => 20,
                'gambar' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategori' => 4,
                'kode_barang' => 'PRL-001',
                'nama_barang' => 'Obeng Set',
                'satuan' => 'set',
                'harga_beli' => 25000,
                'harga_jual' => 35000,
                'stok_min' => 3,
                'stok_saat_ini' => 15,
                'gambar' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategori' => 4,
                'kode_barang' => 'PRL-002',
                'nama_barang' => 'Tang Kombinasi',
                'satuan' => 'pcs',
                'harga_beli' => 18000,
                'harga_jual' => 25000,
                'stok_min' => 4,
                'stok_saat_ini' => 12,
                'gambar' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategori' => 5,
                'kode_barang' => 'LNN-001',
                'nama_barang' => 'Masker Kain',
                'satuan' => 'pcs',
                'harga_beli' => 2000,
                'harga_jual' => 4000,
                'stok_min' => 50,
                'stok_saat_ini' => 300,
                'gambar' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kategori' => 5,
                'kode_barang' => 'LNN-002',
                'nama_barang' => 'Sarung Tangan',
                'satuan' => 'pasang',
                'harga_beli' => 5000,
                'harga_jual' => 8000,
                'stok_min' => 30,
                'stok_saat_ini' => 100,
                'gambar' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
